baseURL = "https://geeklaunch.io"
copyright = "Jacob Lindahl"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]
googleAnalytics = "G-DMBPKLBF8X"
hasCJKLanguage = true
ignoreFiles = ["\\.psd$"]
languageCode = "en-us"
title = "GeekLaunch"

[author]
name = "Jacob Lindahl"

[params]
description = "Tech tips and tutorials. Computer science educational videos, tutorials, guides, blog posts about Rust programming, blockchain, optimization problems, cybersecurity."
logo = "img/geeklaunch.png"
mastodon = "geeklaunch@techhub.social"
twitter = "Geek_Launch"
youtube = "GeekLaunch"

[markup.goldmark.renderer]
unsafe = true

[markup]
[markup.highlight]
anchorLineNos = false
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = ""
lineNos = false
lineNumbersInTable = false
noClasses = false
style = ""
tabWidth = ""

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Posts"
url = "/blog/"
weight = 15

[[menu.main]]
identifier = "youtube"
name = "YouTube"
url = "https://www.youtube.com/c/GeekLaunch?sub_confirmation=1"
weight = 20

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "https://weareindy.com/app/shared/forms/634577ccb25f8365f4aa7f42/zw1Icw3aBtCI90eLSzQVkpZiigUEBLHeaNKmJobnx4kTaPYMixQM3gDZMCFDsSHC/"
weight = 30

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
