baseURL = "https://geeklaunch.net"
languageCode = "en-us"
title = "GeekLaunch"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "geeklaunch"
ignoreFiles = [ "\\.psd$" ]

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    noClasses = false
