baseURL = "https://geeklaunch.io"
copyright = "Jacob Lindahl"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
hasCJKLanguage = true
ignoreFiles = ["\\.psd$"]
languageCode = "en-us"
title = "GeekLaunch"

[params]
description = "Tech tips and tutorials. Computer science educational videos, tutorials, guides, blog posts about Rust programming, blockchain, optimization problems, cybersecurity."
logo = "img/geeklaunch.png"
mastodon = "geeklaunch@techhub.social"
twitter = "Geek_Launch"
youtube = "GeekLaunch"
contact = "https://docs.google.com/forms/d/e/1FAIpQLSfL9-JbBMUk2m4D31KouzAHntMtMOb9LOi7uQNiXYX6XEQhiQ/viewform?usp=sf_link"

[params.author]
# Site author
name = "Jacob Lindahl"

# Specific article authors
[params.author."Jacob Lindahl"]
bio = """
Jacob Lindahl is a graduate student at the [Tokyo Institute of Technology](https://www.titech.ac.jp/) and senior partner engineer at [Matter Labs](https://matter-labs.io/).

Connect with Jacob on [Twitter](https://twitter.com/sudo_build), [Mastodon](https://infosec.exchange/@hatchet), and [Farcaster](https://warpcast.com/hatchet).
"""

[params.plausible]
host = "plausible.c0d3r.dev"
domain = "geeklaunch.io"

[[params.payment]]
name = "BTC"
identifier = "bc1qepmfn0z26tfhc5uys49t3mthgh5q6hat4kp7hf"

[[params.payment]]
name = "ETH"
identifier = "0xA65E766783C23A230A69281BE33B0Aa765008606"

[[params.payment]]
name = "XMR"
identifier = "89LKw5TZx6qiBfDFMzp8nK1ZnmvRvQzGceHAwGSu1TAH6b88imhBZApJpBS85RYbxebhnMpCEVT6BA85gWZV5ZGo1FZhJoP"

[markup.goldmark.renderer]
unsafe = true

[markup]
[markup.highlight]
anchorLineNos = false
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = ""
lineNos = false
lineNumbersInTable = false
noClasses = false
style = ""
tabWidth = ""

[outputs]
home = ["HTML", "RSS"]

[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "blog"
name = "Posts"
url = "/blog/"
weight = 15

[[menu.main]]
identifier = "youtube"
name = "YouTube"
url = "https://www.youtube.com/c/GeekLaunch?sub_confirmation=1"
weight = 20

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "https://docs.google.com/forms/d/e/1FAIpQLSfL9-JbBMUk2m4D31KouzAHntMtMOb9LOi7uQNiXYX6XEQhiQ/viewform?usp=sf_link"
weight = 30

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
